spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: ""
  mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: "" # Use environment variables for better security
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

server:
  port: 8080
